In [1]:
import matplotlib.pyplot as plt

In [2]:
img = plt.imread("image.jpg")

In [3]:
img

array([[[169, 169, 169],
        [169, 169, 169],
        [169, 169, 169],
        ...,
        [ 43,  43,  43],
        [ 43,  43,  43],
        [ 43,  43,  43]],

       [[169, 169, 169],
        [169, 169, 169],
        [169, 169, 169],
        ...,
        [ 43,  43,  43],
        [ 43,  43,  43],
        [ 43,  43,  43]],

       [[169, 169, 169],
        [169, 169, 169],
        [169, 169, 169],
        ...,
        [ 43,  43,  43],
        [ 43,  43,  43],
        [ 43,  43,  43]],

       ...,

       [[175, 175, 175],
        [175, 175, 175],
        [175, 175, 175],
        ...,
        [ 40,  40,  40],
        [ 40,  40,  40],
        [ 40,  40,  40]],

       [[175, 175, 175],
        [175, 175, 175],
        [175, 175, 175],
        ...,
        [ 40,  40,  40],
        [ 40,  40,  40],
        [ 40,  40,  40]],

       [[175, 175, 175],
        [175, 175, 175],
        [175, 175, 175],
        ...,
        [ 40,  40,  40],
        [ 40,  40,  40],
        [ 40,  40,  40]]

In [4]:
import numpy as np

In [5]:
svd = np.linalg.svd(img, compute_uv = False)

In [6]:
len(svd)

1440

In [7]:
svd

array([[1.13501036e+04, 1.50010943e-12, 5.76861857e-28],
       [1.13067275e+04, 5.17000772e-13, 0.00000000e+00],
       [1.12518521e+04, 1.72102653e-12, 0.00000000e+00],
       ...,
       [7.68989850e+03, 2.53403389e-13, 0.00000000e+00],
       [7.68875185e+03, 6.38492624e-13, 6.13493136e-29],
       [7.71788449e+03, 2.31467771e-13, 2.21430635e-29]])

In [8]:
arr = np.array([[2.2, 0.4, 1.6, 2.0, 2.9, 0.8, 1.3, 1.1, 2.3], [2.1, 0.6, 2.3, 2.1, 2.8, 1.1, 1.4, 1.0, 2.6]])

In [9]:
arr

array([[2.2, 0.4, 1.6, 2. , 2.9, 0.8, 1.3, 1.1, 2.3],
       [2.1, 0.6, 2.3, 2.1, 2.8, 1.1, 1.4, 1. , 2.6]])

In [11]:
ev = np.linalg.eig(arr)

LinAlgError: Last 2 dimensions of the array must be square

In [13]:
arr1 = np.array([[1,2,4],[7,9,12],[4,5,23]])
ev = np.linalg.eig(arr1)

In [14]:
ev

(array([27.46485091, -0.50068391,  6.03583299]),
 array([[-0.16440298, -0.81392155, -0.12941822],
        [-0.5805685 ,  0.58078193, -0.94244746],
        [-0.79744083,  0.01496878,  0.3082916 ]]))

In [16]:
cov = np.cov(arr)

In [17]:
cov

array([[0.63944444, 0.58555556],
       [0.58555556, 0.59944444]])

In [18]:
ev = np.linalg.eig(cov)

In [19]:
ev

(array([1.20534146, 0.03354743]),
 array([[ 0.7190743, -0.6949332],
        [ 0.6949332,  0.7190743]]))